user_user:
    resource: "@UserBundle/Controller/UserController.php"
    type:     annotation

rhxml_reader:
    resource: "@RHXMLReaderBundle/Resources/config/routing.yml"
    prefix:   /admin

rhxml_reader_s2220:
    resource: "@RHXMLReaderBundle/Controller/S2220XMLReaderController.php"
    type:     annotation

rhxml_reader_s2240:
    resource: "@RHXMLReaderBundle/Controller/S2240XMLReaderController.php"
    type:     annotation

login_user:
    resource: "@UserBundle/Resources/config/routing.yml"

homepage:
    resource: "@RHXMLReaderBundle/Controller/DefaultController.php"
    type:     annotation
    prefix: /
