# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
      gedmo.listener.loggable:
              class: Gedmo\Loggable\LoggableListener
              tags:
                  - { name: doctrine.event_subscriber, connection: default }
              calls:
                  - [ setAnnotationReader, [ "@annotation_reader" ] ]

      extension.listener:
              class: RH\XMLReaderBundle\Listener\DoctrineExtensionListener
              calls:
                  - [ setContainer, [ "@service_container" ] ]
              tags:
                  # loggable hooks user username if one is in security context
                  - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }