<?php

namespace RH\XMLReaderBundle\Repository;

/**
 * FileFuncionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileFuncionarioRepository extends \Doctrine\ORM\EntityRepository
{
}
