<?php

namespace RH\XMLReaderBundle\Repository;

use RH\XMLReaderBundle\Entity\Funcionario;

/**
 * FuncionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionarioRepository extends \Doctrine\ORM\EntityRepository
{


    public function insertFuncionario(array $coluna)
    {
        $em = $this->getEntityManager();

        $funcionario = new Funcionario();

        $funcionario->setNome($coluna[1])
            ->setCpf($coluna[2])
            ->setDrt($coluna[0])
            ->setPis($coluna[3])
            ->setStatus(true);

        $em->persist($funcionario);

    }

    public function updateFuncionario(Funcionario $funcionario)
    {

        $em = $this->getEntityManager();

        $em->persist($funcionario);

    }

    public function consultaCPF($cpf)
    {
        $funcionario = $this->getEntityManager()
                            ->getRepository('RHXMLReaderBundle:Funcionario');

        $funcionarioEncontrado = $funcionario->findOneBy(array('cpf' => $cpf));

        return $funcionarioEncontrado;
    }

}
