<?php

namespace RH\XMLReaderBundle\Repository;

/**
 * S2220tpasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S2220tpasoRepository extends \Doctrine\ORM\EntityRepository
{
}
