<?php

namespace RH\XMLReaderBundle\Repository;

/**
 * S2220eS2240SimNaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S2220eS2240SimNaoRepository extends \Doctrine\ORM\EntityRepository
{
}
