<?php

namespace RH\XMLReaderBundle\Repository;

/**
 * S2240utilizepcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S2240utilizepcRepository extends \Doctrine\ORM\EntityRepository
{
}
