<?php

namespace RH\XMLReaderBundle\Repository;

/**
 * tpasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tpasoRepository extends \Doctrine\ORM\EntityRepository
{
}
