services:
#    rhxml_reader.example:
#        class: RH\XMLReaderBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
      rhxml_reader.validateXml:
         class: RH\XMLReaderBundle\Service\ValidatorXml